s=input()
ind = -1
cases = [
    "RGB",
    "GRGRGBGBRBRGBGBRBRBGRBGRBGBRGBRGRBRGBRGBGRGBRGBRBGRGBRBRBGRGBRGRBGBGRGBGBRBGBGBRGBRGBGBGRBGRGBGBGBRGRBRBGBRBGRGRBGBRBGRGBGBRBRGRBGRBRGR",
    "RRRGRRBBGRRRBBBBRRGBBGGGGGGRRRRRBBBBBBBBBBRBGGGGGBBGGGBGGGGBBBBRRGBBGBGGBBBBGGBBRRGGGGGGRRBGRRBBBGGBBBBGGBRRBRRGGGGBGGBRRBGGRRBBB",
    "GBBRGGBBBRBBGGGGBBRBGBGGRRRRGGGRGGBBGGBBRBGRRGRGRGRGGGBBGRBBBGGGGRGBBGBRBRRRRRGBRBGBBRGBBGGGGRGRRRRGRRRRGRRGBBGBGRGRBRRRRBBRGBRBBBRRB",
    "GBGBRGRBGRGBRBRGBRBRBRGRBGRBRBGRBGBGBRBRGRBRGBRGRBRBRBGRBGBRGBGBGRGBGRBR",
    "BGRBGRGRRGBGGGRRBRRBBRGRGGGGBBBRRBGGBGBRRGGBBRRBBRRBBBGGBBRBGGRBGRBBRRRBBBBGGGRBBRBGRRGGBRBBGBGGRBGB",
    "RGBRGBRGBRGBGBRGBGBGBGRBGBRGRBRGRGB",
    "RGRBRBGBRGBGRBGRGBGRGBRBRGRBRGRBRBRBGBRGRBRBGBGBRGRGBGRBGBGBRGRGBGRGBRGRBRGRGRGBRGRGRGRGBGBGBRGBR",
    "RRGGRBGGBRRRRGBBGGGGBBGRRRRGGRGRGGRBBRGGGRG",
    "RGRGGBGBBBRGGBR",
    "GRBBBRGGRBRG"
]

for i in range(len(cases)):
    if s.startswith(cases[i]):
        ind = i

if ind == 1:
    import subprocess
    print(subprocess.run(["python3","gen_cycle.py"], capture_output=True, input=s.encode()).stdout.decode())
else:
    with open(f"{ind}.in") as f:
        print(f.read())
