#!/bin/bash
PPATH=$(realpath ..)
. ../../testdata_tools/gen.sh

setup_dirs
use_solution js.cpp
compile generator_random.py

samplegroup
sample 1
sample 2

group nonormalize 23
tc g1-1 generator_random med=50 max=100
tc g1-2 generator_random med=50 max=100
tc g1-3 generator_random med=50 max=100
tc g1-4 generator_random med=50 max=100
tc g1-5 generator_random med=50 max=100

group firstyears 13
tc g2-1 generator_random age=1
tc g2-2 generator_random age=1
tc g2-3 generator_random age=1
tc g2-4 generator_random age=1
tc g2-5 generator_random age=1

group samekatt 31
tc g3-1 generator_random katt=1
tc g3-2 generator_random katt=1
tc g3-3 generator_random katt=1
tc g3-4 generator_random katt=1
tc g3-5 generator_random katt=1

group all 33
include_group nonormalize
include_group firstyears
include_group samekatt
tc g4-1 generator_random
tc g4-2 generator_random
tc g4-3 generator_random
tc g4-4 generator_random max=700 med=4
tc g4-5 generator_random max=700

generate_grader
cleanup_programs
