#!/bin/bash
PPATH=$(realpath ..)
. ../../testdata_tools/gen.sh

setup_dirs
use_solution karl_ac.py
compile generator_random

samplegroup
sample 1
sample 2

group fixednums 30
tc g1-1 generator_random fixedNums noSpaces n=100
tc g1-2 generator_random fixedNums noSpaces n=100
tc g1-3 generator_random fixedNums noSpaces n=100
tc g1-4 generator_random fixedNums noSpaces n=100
tc g1-5 generator_random fixedNums noSpaces n=100

group nospaces 20
tc g2-1 generator_random noSpaces numMax=10 n=1000
tc g2-2 generator_random noSpaces numMax=10 n=1000
tc g2-3 generator_random noSpaces numMax=10 n=1000
tc g2-4 generator_random noSpaces fixedNums n=1000
tc g2-5 generator_random noSpaces fixedNums 10 n=1000


group small 20
tc g3-1 generator_random numMax=100 n=1000
tc g3-2 generator_random numMax=100 n=1000
tc g3-3 generator_random numMax=100 n=1000
tc g3-4 generator_random numMax=100 n=1000
tc g3-5 generator_random numMax=10 n=1000
tc g3-6 generator_random fixedNums n=1000

group all 30
include_group fixednums
include_group nospaces
include_group small
tc g4-1 generator_random numMax=1000 n=100000
tc g4-2 generator_random numMax=1000 n=100000
tc g4-3 generator_random numMax=100 n=100000
tc g4-4 generator_random numMax=100 n=100000
tc g4-5 generator_random numMax=10 n=100000
tc g4-6 generator_random numMax=10 n=100000
tc g4-7 generator_random fixedNums n=100000
tc g4-8 generator_random fixedNums n=100000

generate_grader
cleanup_programs
